# Imagen oficial de MongoDB
FROM mongo:6.0

# Copiar scripts de inicialización si los tienes
# (Por ejemplo, crear colecciones o insertar datos)
# COPY ./init-scripts/ /docker-entrypoint-initdb.d/

# Puerto que expone MongoDB
EXPOSE 27017

# Comando por defecto
# CMD ["mongod"]
